id: P008037
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22787
  title: ཀརྨ་སི་ཏུའི་སུམ་རྟགས་འགྲེལ་ཆེན།
  author: ''
  volumes:
    9fa12879fe6843c1bb8957826f7a6f1e:
      image_group_id: I4741
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
